### ISSUE TITLE
item.categories are not optional

### ISSUE THREAD

**Issue by jaredkotoff** [dylang/node-rss#118]
My feed items do not have categories, and the docs list this as optional.

When running `feed.xml()`:
```
TypeError: undefined is not an object (evaluating 'item.categories.forEach')
      at /node_modules/rss/lib/index.js:71:9
      at forEach (:1:21)
      at generateXML (/node_modules/rss/lib/index.js:63:5)
      at /node_modules/rss/lib/index.js:185:17
```

When I change: 
```js
item.categories.forEach(function(category) {
            ifTruePush(category, item_values, { category: { _cdata: category } });
        });
```

to 
```js
item.categories?.forEach(function(category) {
            ifTruePush(category, item_values, { category: { _cdata: category } });
        });
```

I am able to generate the xml feed

**Comment by adriancuadrado** [comment]
It should be optional. Or at least according to the RSS spec:
* [Channel](https://www.rssboard.org/rss-specification#optionalChannelElements) ![Image](https://github.com/user-attachments/assets/ce5cad96-3f82-4bf3-bba2-89978fb559be)
* [Item](https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt) ![Image](https://github.com/user-attachments/assets/2e1efd77-adfd-4345-9fd4-cdcba7d21032)
